### ISSUE TITLE
[JOSS Review] Installation instructions

### ISSUE THREAD

**Issue by GregaVrbancic** [nedRad88/SCALAR#3]
Hello @nedRad88, I am the reviewer of your SCALAR paper on JOSS  openjournals/joss-reviews/issues/2676. While there are installation instructions available utilizing Docker and docker-compose technology, I think it would be beneficial to also include the python dependencies list in the documentation. Ideally, the python dependecy should be maintained using package management tools such as pip, poetry, pipenv.

**Comment by xiaohk** [comment]
Hello @nedRad88, I am another reviewer for your JOSS submission.

I am following the installation instruction on README, and have some problem to run the platform in my browser. I am currently stuck at the step to install `sql_db` container. I also wonder how to run the app after all these dependences are installed; can I just run `docker run`?

The installation instruction would be much better if it lists _all exact commands_ that users need to run, in order to open this web app in their browsers.

**Comment by nedRad88** [comment]
Hello @xiaohk,
Thanks for the comments.
Did you manage to finish the installation? If not can you tell me what is the problem that you face? After installing `Docker`, `Docker compose` and setting `config.json` and `docker-compose.yml` according to instructions, you run `docker-compose up` and it will pull all necessary containers and run them. I will make the instructions more clear and come back to you.

**Comment by xiaohk** [comment]
Thanks for your promptly reply.

Can you please also provide some instruction for installing `sql_db`? Thanks!

**Comment by nedRad88** [comment]
Hello @xiaohk,
Did you mean for installing mysql-client? We are working on improving the installation instructions and now this step has been removed. Now, `docker-compose up` will start the platform. You just need the latest version of the code.

**Comment by nedRad88** [comment]
Hello @GregaVrbancic @xiaohk , I have updated the installation instructions. There is an option for quick setup when you want just to check the functionality of the platform. According to this, I will create a simplified scenario to test the functionality.
